
on: push

jobs:
  publish:    
    permissions:
      packages: write
      contents: write
      actions: write  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: devcontainers/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        publish-features: "true"
        base-path-to-features: "./src"